### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by zivillian** [zivillian/ism7mqtt#33]
this issue is primarily to discuss, what's the best way to integrate this into HA and what needs to be done.

**Comment by zivillian** [comment]
Since I don't use HA (at the moment) I don't really know the possibilities, up- and downsides and best practices. Also I don't have any expectations and can't test anything.

This are my current bulletpoints:

- separate repository?
- MQTT autodiscovery?
- hvac?
- i18n
- migration from [wolflink](https://www.home-assistant.io/integrations/wolflink)
- how to generate parameter.json from scratch with HA?
- run ism7mqtt within HA?

If anyone has any input, don't hesitate to comment below.

**Comment by infocfc** [comment]
I use HA. I think for the average user, the by far most important part would be to get MQTT Discovery working. Manually adding the Topics is cumbersome, and also has a lot of downsides, like not being able to use Devices (each Topic becomes an individual Entity, and can't be grouped to a device). The workaround is to actually create scripts that feed the Discovery process, so that Devices with multiple topics/entities become possible but that's even more manual work, and IMHO most users shy away from that.

Running ism7mqtt on HA itself is certainly possible, but I wouldn't make it a priority. Likewise migration from wolflink, I personally don't think it's worth the effort, especially as both can run in parallel anyways.

Is i18n an issue? I dont know if Wolf heatings are common in non-german speaking countries. Where exactly do the german texts come from anyways?

Hvac, I don't know. Technically, it isn't, IMHO. I don't consider it necessary. I'd be really happy to be able to be able switch stuff on and off, and to be able to change target temperatures.

If you need someone to test, I'd be happy to.

**Comment by zivillian** [comment]
>Where exactly do the german texts come from anyways?

The german texts are part of the [XML definition](https://github.com/zivillian/ism7mqtt/blob/master/src/ism7mqtt/Resources/ParameterTemplates.xml) I extracted from the Wolf Smartset Application.

**Comment by testkandidat** [comment]
I am really looking forward to an integration for Home Assistant.

**Comment by zivillian** [comment]
Thanks to @b3nn0 we now have a first version to test in #35
