### ISSUE TITLE
No periodical updates for several ism7 values

### ISSUE THREAD

**Issue by krkuhlmann** [zivillian/ism7mqtt#42]
I have an issue with some of the values only being updated directly after starting the container and not being updated anymore. I switched on debugging and there are only a subset of values on the same bus 0x08 that get updated every now and then.
I would be fine with it if that was because of the values not having changed between queries but the smart set portal and the value on the display of the BM-2 terminal show different values.
Any ideas?

**Comment by krkuhlamnn** [comment]
The more i look into the code, the mre I get the feeling that this issue has nothing to do with the service itself. It seems to me that the ISM7 does not accept the `InfoRead.Intervall` Property or at least it does not send updates even if the value changes. I think it would be gool to have a separate `forceUpdate_parameter.json` with the same structure of the `parameter.json` file containing those parameter that get manually refreshed by the service by explicitely sending another `TelegramBundleReq` every `{Interval}` seconds containing only `InfoRead`Telegrams for those parameters where ism7 does not send updates for automatically.

**Comment by krkuhlamnn** [comment]
I have adapted the code to meet my requirements and it's working so far. I would like to to tak a look into it and maybe merge it. But how do i do this? I can't push to your repository.

**Comment by zivillian** [comment]
Just create a fork, push your changes there and open a PR: https://docs.github.com/de/get-started/quickstart/contributing-to-projects

But I'd like to go one step back. Can you upload you smartset db, so I can look at your parameters? I also would like to check how the smartset app behaves. Maybe we need to request something else or are missing a parameter.

**Comment by zivillian** [comment]
Do you have an example for a parameter which is not reported despite changed values?

**Comment by zivillian** [comment]
I have a guess what's wrong. Those parameters are of type UINT32 and consist of two telegrams each (high and low). If the ISM only sends the changed low telegram the converter waits until it also get's a changed high value.

There was a similar bug with the solar statistics converter.

To confirm this it would be great if you can modify your paramter.json to contain only the three affected parameters and let it run for an hour or so with debug output enabled. I expect to see push reponses from the ism but no MQTT update, because only half of the required telegrams is received.

PS: When posting your debug log, please remove the password

**Comment by zivillian** [comment]
Should be fixed in master - can you test if this now also works for you?
